### ISSUE TITLE
Driver using player, Physical buttons do not work as expected.

### ISSUE THREAD

**Issue by nklerk** [NEEOInc/neeo-sdk#120]
While using the SDK Player, physical buttons do not work.
while Channel Up and Down are mapped to next/previous track buttons.

I'm requesting the same workings as without the player component.

**Comment by MichaelKohler** [comment]
Thanks for filing this issue. I've had a look:

* CURSOR ENTER -> we are mapping the "OK" physical button to "PLAY PAUSE" right now, which as far as I see does not exist in your buttons. Happy to discuss if this should be made more general, though I think it fits nicely with the MUSICPLAYER theme. However, we might want to improve the docs around that. Do you have a specific idea regarding this one as a user?
* Volume Down / Up -> this is a bug and will be fixed in the 0.52.x series
* LEFT, RIGHT, UP, DOWN, MENU is currently not mapped. Can you share some use cases you think would be valuable to support? If there are any, I'm sure we could add these if they exist in the driver.
* MUTE -> as with Kodi the Volume is through the TV, we are also sending the mute to the TV, and therefore it will never come down to your SDK device. Can you verify that MUTE works for the TV you've wired it up to?

Hope this helps, looking forward to your feedback.

**Comment by nklerk** [comment]
Michu asked me to include the player into my kodi driver so I did. Thing is that with a player that utilizes a screen you always want to be able to use the directional buttons.

I don’t mind that physical buttons are mapped based on button names but when they are not consistently used it becomes a mess in my honest opinion.

Now the play/pause is mapped to OK. Why not send CURSOR OK and let the driver handle what it does.

**Comment by MichaelKohler** [comment]
> Thing is that with a player that utilizes a screen you always want to be able to use the directional buttons.

Fair enough, I think that's a valid use case. I personally would probably not use anything on the screen anymore if I had everything I need in the player.

**Comment by nklerk** [comment]
Although the list function is especially great when looking for recently added content it’s less suitable for browsing a large library (500+ items) and the UI is more suitable.

Also onscreen keyboards, settings, language changes are things that are common.

**Comment by nklerk** [comment]
Here is a demo of the TR2 not having a working PLAY/PAUSE. https://youtu.be/uv3cQXBwW5M The OK button once the "PLAY PAUSE" button was added does it's job. also visible in the video.

On EUI the Play/Pause button just works normal.
https://youtu.be/2Tyt5p_FT08

Volume UP/Down indeed won't work.
Mute works.

As my expectations about the player component where wrong. I'll close the issue.
