### ISSUE TITLE
Support for scenario creation

### ISSUE THREAD

**Issue by tmrobert8** [NEEOInc/neeo-sdk#21]
Again - using russound as an example.  Would be nice to able to define a 'Listen to Music' scenario that would startup a device automatically in a specific room (russound zone).

**Comment by neophob** [comment]
recipes do already support sending custom commands to devices, what excactly do you miss? or in other words, what value your request would add?

**Comment by tmrobert8** [comment]
I'm thinking of the Apple TV scenario where you press on it and it runs the poweron recipe, shows some controls (with the shortcuts screen) and shows up on the remote as a scenario with the poweroff button.  I'd love a "Listen to Music" scenario that would startup my Russound, show my custom widget and I simply press the scenario "off" to turn everything off.

**Comment by neophob** [comment]
Hmm sorry I can't follow you here. Are you talking about the recipe name ("Listen to Music"), custom widget support or something different?

Because the "Apple TV" use case you describe is already there and is the core functionality of the NEEO Brain. You add a device, the recipe prepare the device, you can use it. So that *should* already work with the SDK - so maybe it's just unclear / not documented.

**Comment by tmrobert8** [comment]
Yeah - I don't think I'm exactly clear on this because I'm still unsure of what the terminology you use is.  I believe I'm stating - I want to be able to create a recipe that says "Listen to Music" and have the recipe/scenario/? show up in the active lines on the remote (where it shows the name and gives you the power off capability)

**Comment by tmrobert8** [comment]
Ah - now that I'm learning more about it - I see that active line is based on the adapter type and capabilities
