### ISSUE TITLE
Notifications to a switch expects string-false and boolean-true

### ISSUE THREAD

**Issue by nklerk** [NEEOInc/neeo-sdk#27]
When sending a state update to a switch it only works. when providing false as a string and true as a boolean.

updateComponent(deviceId, 'toggle', 'false');
updateComponent(deviceId, 'toggle', true);

í Couldnt find the root cause.

**Comment by tmrobert8** [comment]
It's probably line 22 in notification.js - they are trying to detect and empty notification (but false and 0 will also be caught up).  Personally - I think this line should be removed (or atleast 'msg!==undefined && msg!==null') because an empty string can be a valid message (say a textlabel that shows some error or status information and an empty string would clear it)

**Comment by neophob** [comment]
Hi

the `notification.js` class would not send a notification if you would just send false, thats true.

however if you take a look at `device/brain/index.js`, function `sendNotification` you see that each notification is composed as 

`const notificationData = { type: notificationKey, data: msg.value };`

anyway @nklerk - do you have the code somewhere available so I can take a look?

**Comment by tmrobert8** [comment]
Good point!

**Comment by nklerk** [comment]
I just found the issue, it's the way I validated the value. Sorry for this report.

function updateComponent(uniqueDeviceId, component, value){
  if (sendComponentUpdate && uniqueDeviceId && component && value) {

    sendComponentUpdate({
      uniqueDeviceId: uniqueDeviceId,
      component: component,
      value: value
    })
    .catch((error) => {
      console.log('[CONTROLLER] Failed to send notification', error.message);
    });

  }
}
