### ISSUE TITLE
LIFX Example integration

### ISSUE THREAD

**Issue by neophob** [NEEOInc/neeo-sdk#5]
# Feature Request
- create a example integration for LIFX light bulbs using the NEEO SDK, using the https://github.com/NEEOInc/neeo-community-adapter

# CoS
- add LIFX implementation as illustration example

**Comment by GeertWille** [comment]
I added an LIFX example on neeo-sdk-examples Github. you can see the pull request [here](https://github.com/NEEOInc/neeo-sdk-examples/pull/2).

**Comment by neophob** [comment]
Thanks @GeertWille for the first working version. I think the following (minor) features might improve the adapter:

- Discrete Power commands for a single lamp (Power on / Power off)

@GeertWille maybe you know more - there is currently no other option to control the LIFX lamp but communicate with the public REST (cloud) API? Like can we communicate directly with the LIFX lamp?

**Comment by GeertWille** [comment]
@neophob what do you mean exactly with the Discrete Power commands for a single lamp? There is a power toggle button right now for every bulb?

Yes it is possible to use the [lan-api](https://lan.developer.lifx.com/) though I didn't find a good node implementation of it yet that's why I started with the Cloud API. I'll take a look or I can write a node implementation for the lan-api myself or if you find a good one let me know ;).

**Comment by nklerk** [comment]
@GeertWille This one looks interesting. https://github.com/MariusRumpf/node-lifx

**Comment by GeertWille** [comment]
@nklerk Cool, I'll try to make time and make an example ;)

**Comment by neophob** [comment]
@GeertWille @nklerk sounds interesting. the local lan protocol *might* be easier to implement - we dont need an API key. and it looks like discovery is also supported.

@GeertWille: with "Discrete Power commands" I mean a power on/off button. for example you want to power on your lights when a sensor triggers - then the power toggle is not the best option if you want to ensure the lights are on

**Comment by neophob** [comment]
thanks @nklerk and @GeertWille, will be included with the next release!
