### ISSUE TITLE
[Feature Request] Add callback at the end of discovery process and just after user select desired device.

### ISSUE THREAD

**Issue by Krikroff77** [NEEOInc/neeo-sdk#53]
The function registered with registerInitialiseFunction is called too late and in some situations it is necessary to perform an action (example loading data for configuration) when the user selects the device after the discovery process.

.registerAfterDiscoveryFunction(controller.afterDiscovery)

// Example code in the controller:
module.exports.initialise = function() {
  debug('call api and load some data from home automation device');
  // dynamically add switches or buttons
};

Regards

**Comment by neophob** [comment]
Hi @Krikroff77 

Thats possible but I think that would make the SDK too complicated. You could for example do a lazy initialisation of your controller, the first time a device is used in a controller you can load the needed data.

Did you take a look for example what the LIFX example does: https://github.com/NEEOInc/neeo-sdk-examples/blob/master/lib/device/lifx-local/lifxcontroller.js?

**Comment by Krikroff77** [comment]
Hi @neophob thanks you for your quick reply ;)

I'm already using lazy initialisation but that does not exactly answer the need.
The goal is to build dynamically the buttons or switches the first time so i can use them in recipes.

I think the only solution today and not to use a discovery service unfortunately. It is therefore necessary to prepare in a configuration file, load the data and only then create the device. The limit of this architecture is the impossibility to update then ...

Example:
**1.** At the creation of the device I can have

switch1: scene 1
switch2: scene 2
etc ..

**2.** If I add a new scene to my home automation controller, I have no way to update the device and add a new switch to the adapter


br,

**Comment by neophob** [comment]
Not sure If I really understand you issue. I think discovery has nothing to do with your request, I think you want something like https://github.com/NEEOInc/neeo-sdk/issues/52 - correct?

**Comment by Krikroff77** [comment]
Yes and no ;)

I really think that the callback registered with registerInitialiseFunction is raised too late. Handle process just after discovery & user action is the right place, this request is complementary with https://github.com/NEEOInc/neeo-sdk/issues/52.

**Use case**:

**If we supposed you add the ability to add dynamically** buttons AND if i use registerInitialiseFunction to create and add buttons/switches/sliders it will never work because callback "initialise" will never called because at this time there are no buttons/switches  expose by device ;)

**Comment by nklerk** [comment]
What I think is that you want is the ability to construct the device capabilities dynamically after the device is selected at the discovery proces. Is this correct?

This is something Tim and myself ran in to when we wanted to build intergrations for other systems.

**Comment by neophob** [comment]
I changed the text of #52 - where the request is adding favorites (as its called today) - but that feature can be used to add the dynamic part of a device.

the idea of the `registerInitialiseFunction` is, that you can start initialising tasks like starting a discovery service. this function is called when the first request for that device is handled - so there is no such thing as "too late" in this context.

What exactly do you try to do?

**Comment by pfiaux** [comment]
As @neophob said if you need dynamic elements based on 'live' data from the device, favorites #52 or lists #8 would cover that. This is will be the way to go for data that might be short lived on the SDK device and could be removed at any time since it will be queried just in time.

If a device has new functionality that would be covered by updates via #18, this will add the ability to update, add or remove buttons. However it isn't meant to be used to create buttons for 'live' data, it needs represent the capability of the device. That's because buttons could be added as recipe steps or shortcuts and if they're all of a sudden removed it can be problematic and confusing.

As a work around currently using favorite switches (switch A, switch B, and switch C) might be the best option.
The Brain sees 3 switches, but on the SDK you're free to reassign them to different scene, switch A could be using scene 1, but then switched to scene 2 without the Brain having to know anything except if the state changed. It might do the trick in a limited way until the features mentioned above are released.
